# Generated by Django 4.1.7 on 2023-03-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0005_alter_item_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='body',
            field=models.CharField(max_length=50),
        ),
    ]
