# Generated by Django 4.1.7 on 2023-03-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0006_alter_item_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='body',
            field=models.CharField(max_length=50, verbose_name='New Item'),
        ),
    ]
